'use client';

import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { questionsApi } from '@/services/api';
import { Button, Badge, Skeleton, EmptyState, Modal, Alert, Pagination } from '@/components/ui';
import { truncate } from '@/lib/utils';

export default function AIDraftsPage() {
  const qc = useQueryClient();
  const [page, setPage]     = useState(0);
  const [preview, setPreview] = useState<number | null>(null);
  const [alert, setAlert]   = useState<{ type: 'success' | 'error'; msg: string } | null>(null);

  const { data, isLoading } = useQuery({
    queryKey: ['admin-drafts', page],
    queryFn: async () => {
      const res = await questionsApi.getDrafts({ page, size: 20 });
      return res.data.data;
    },
  });

  const selected = data?.content.find(q => q.id === preview);

  const approveMutation = useMutation({
    mutationFn: questionsApi.approve,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['admin-drafts'] });
      setAlert({ type: 'success', msg: 'Question approved (→ APPROVED).' });
    },
    onError: () => setAlert({ type: 'error', msg: 'Failed to approve question.' }),
  });

  const publishMutation = useMutation({
    mutationFn: questionsApi.publish,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['admin-drafts'] });
      setAlert({ type: 'success', msg: 'Question published and live.' });
    },
    onError: () => setAlert({ type: 'error', msg: 'Failed to publish question.' }),
  });

  const deleteMutation = useMutation({
    mutationFn: questionsApi.delete,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['admin-drafts'] });
      setPreview(null);
      setAlert({ type: 'success', msg: 'Draft deleted.' });
    },
    onError: () => setAlert({ type: 'error', msg: 'Failed to delete draft.' }),
  });

  return (
    <div className="space-y-5 animate-in">
      {alert && <Alert type={alert.type} message={alert.msg} onClose={() => setAlert(null)} />}

      {/* Info Banner */}
      <div className="bg-violet-50 dark:bg-violet-950/50 border border-violet-200 dark:border-violet-800 rounded-xl p-4 flex gap-3">
        <span className="text-2xl">🤖</span>
        <div>
          <p className="font-semibold text-violet-900 dark:text-violet-100 text-sm">AI-Generated Question Review</p>
          <p className="text-violet-700 dark:text-violet-300 text-xs mt-0.5">
            These questions were generated by AI and are in DRAFT status.
            Review each one carefully before Approving or Publishing.
            Workflow: <strong>DRAFT → APPROVED → PUBLISHED</strong>
          </p>
        </div>
      </div>

      {/* Table */}
      <div className="bg-card border border-border rounded-xl overflow-hidden">
        <div className="px-5 py-4 border-b border-border flex items-center justify-between">
          <h3 className="text-sm font-semibold text-foreground">
            Draft Questions ({data?.totalElements ?? 0})
          </h3>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full data-table">
            <thead>
              <tr>
                <th>#</th>
                <th>Question</th>
                <th>Exam / Topic</th>
                <th>Difficulty</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {isLoading ? (
                [...Array(5)].map((_, i) => (
                  <tr key={i}><td colSpan={6}><Skeleton className="h-8 w-full" /></td></tr>
                ))
              ) : data?.content.length === 0 ? (
                <tr>
                  <td colSpan={6}>
                    <EmptyState
                      title="No draft questions"
                      description="AI-generated questions will appear here for review."
                    />
                  </td>
                </tr>
              ) : (
                data?.content.map((q, i) => (
                  <tr key={q.id}>
                    <td className="text-muted-foreground text-xs">{page * 20 + i + 1}</td>
                    <td>
                      <p className="text-sm max-w-xs">{truncate(q.questionText, 70)}</p>
                    </td>
                    <td className="text-xs text-muted-foreground">
                      <p>{q.examName}</p>
                      <p className="opacity-70">{q.topicName}</p>
                    </td>
                    <td>
                      <Badge variant={
                        q.difficulty === 'EASY' ? 'success'
                          : q.difficulty === 'HARD' ? 'destructive'
                          : 'warning'
                      }>
                        {q.difficulty}
                      </Badge>
                    </td>
                    <td>
                      <Badge variant="warning" dot>DRAFT</Badge>
                    </td>
                    <td>
                      <div className="flex gap-1">
                        <Button variant="ghost" size="sm" onClick={() => setPreview(q.id)}>
                          Review
                        </Button>
                        <Button
                          variant="primary"
                          size="sm"
                          loading={approveMutation.isPending}
                          onClick={() => approveMutation.mutate(q.id)}
                        >
                          Approve
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
        {data && data.totalPages > 1 && (
          <Pagination page={page} totalPages={data.totalPages} totalElements={data.totalElements} size={20} onChange={setPage} />
        )}
      </div>

      {/* Preview Modal */}
      {selected && (
        <Modal
          open={!!preview}
          onClose={() => setPreview(null)}
          title="Review Draft Question"
          description="AI-generated · DRAFT status"
          size="lg"
          footer={
            <div className="flex gap-2 w-full">
              <Button
                variant="destructive"
                size="sm"
                loading={deleteMutation.isPending}
                onClick={() => deleteMutation.mutate(selected.id)}
              >
                Delete Draft
              </Button>
              <div className="flex-1" />
              <Button variant="outline" onClick={() => setPreview(null)}>Close</Button>
              <Button
                variant="secondary"
                loading={approveMutation.isPending}
                onClick={() => { approveMutation.mutate(selected.id); setPreview(null); }}
              >
                Approve Only
              </Button>
              <Button
                loading={publishMutation.isPending}
                onClick={() => { publishMutation.mutate(selected.id); setPreview(null); }}
              >
                Approve & Publish
              </Button>
            </div>
          }
        >
          <div className="space-y-4">
            <div className="flex gap-2 flex-wrap">
              <Badge variant={selected.difficulty === 'EASY' ? 'success' : selected.difficulty === 'HARD' ? 'destructive' : 'warning'}>
                {selected.difficulty}
              </Badge>
              <Badge variant="info">{selected.examName}</Badge>
              <Badge variant="default">{selected.topicName}</Badge>
            </div>

            <div className="bg-muted/40 rounded-xl p-4">
              <p className="text-sm font-medium text-foreground leading-relaxed">{selected.questionText}</p>
            </div>

            <div className="space-y-2">
              <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Options</p>
              {selected.options?.map((opt, i) => (
                <div
                  key={opt.id}
                  className={`flex items-center gap-3 p-3 rounded-lg border transition-colors ${
                    opt.isCorrect
                      ? 'bg-emerald-50 border-emerald-200 dark:bg-emerald-950 dark:border-emerald-800'
                      : 'bg-muted/30 border-border'
                  }`}
                >
                  <span className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold shrink-0 ${
                    opt.isCorrect ? 'bg-emerald-500 text-white' : 'bg-muted text-muted-foreground'
                  }`}>
                    {String.fromCharCode(65 + i)}
                  </span>
                  <p className={`text-sm ${opt.isCorrect ? 'text-emerald-800 dark:text-emerald-200 font-medium' : 'text-foreground'}`}>
                    {opt.optionText}
                  </p>
                  {opt.isCorrect && (
                    <span className="ml-auto text-xs text-emerald-600 font-medium">✓ Correct</span>
                  )}
                </div>
              ))}
            </div>

            {selected.explanation && (
              <div className="bg-blue-50 dark:bg-blue-950/50 border border-blue-200 dark:border-blue-800 rounded-xl p-4">
                <p className="text-xs font-semibold text-blue-700 dark:text-blue-300 mb-1">Explanation</p>
                <p className="text-sm text-blue-800 dark:text-blue-200">{selected.explanation}</p>
              </div>
            )}
          </div>
        </Modal>
      )}
    </div>
  );
}
