spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN
    com.rapidstudy: INFO
    org.springframework.security: WARN

# Production-specific settings
server:
  error:
    include-stacktrace: NEVER
    include-message: NEVER

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
